lojaonline/lojaonline/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls)

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lojaonline/main/urls.py
from django.contrib import admin
from django.urls import include, path

from main import views



app_name = 'main'



urlpatterns = [
    path('', views.BaseView.as_view(), name='index'),
    path('', include('django.contrib.auth.urls')),
    path("logar/", views.LogarView.as_view(), name="logar"),
    path("cadastro/", views.CadastroView.as_view(), name="cadastro"),
    path("minha-conta/", views.MinhaContaView.as_view(), name="minha-conta"),
    path("pedidos/", views.PedidosView.as_view(), name="pedidos"),
    path("pedidos/<int:pedido_id>/", views.PedidoView.as_view(), name="pedido"),
    path("carrinho/", views.CarrinhoView.as_view(), name="carrinho"),
    path("finalizar-compra/", views.FinalizarCompraView.as_view(), name="finalizar-compra"),
    path("limpar-carrinho/", views.LimparCarrinhoView.as_view(), name="limpar-carrinho"),
    path("remover/", views.RemoverProdutoView.as_view(), name="remover"),
    path("produto/<slug:slug>/", views.ProcutoView.as_view(), name="produto"),
    path("categoria/mouse/",  views.MouseView.as_view(), name="mouse"),
    path("categoria/teclado/",  views.TecladoView.as_view(), name="teclado"),
    path("categoria/mousepad/", views.MousepadView.as_view(), name="mousepad"),
    path("categoria/fone/", views.FoneView.as_view(), name="fone"),
    path("categoria/monitor/", views.MonitorView.as_view(), name="monitor"),
    path('buscar/', views.BuscarView.as_view(), name='buscar'),
    path("admin/", admin.site.urls),
    
]

lojaonline/main/models.py
from django.conf import settings
from django.db import models
from django.utils.text import slugify 

# Create your models here.

ESCOLHA_CATEGORIAS = (

    (1, ("Mouse")),
    (2, ("Teclado")),
    (3, ("Mousepad")),
    (4, ("Fone")),
    (5, ("Monitor")),
)


STATUS_PEDIDO = (

    (1, ("Aguardando envio")),
    ( 2, ("Enviado")),
    ( 3, ("Entregue")),

)

class Marca(models.Model):
    nome = models.CharField(max_length=50)
    origem = models.CharField(max_length=50, default='BR')

    def __str__(self):
        return self.nome     

class Produto(models.Model):
    nome = models.CharField(max_length=50)
    marca = models.ForeignKey(Marca, default=None,  on_delete=models.CASCADE )
    categoria = models.IntegerField(choices=ESCOLHA_CATEGORIAS)
    preco = models.FloatField(max_length=20, default=0)
    slug = models.SlugField( default='')
    descricao = models.TextField(default='')
    estoque = models.IntegerField(default=0)
    foto = models.ImageField( default='image-cap.png')
    data_pub = models.DateTimeField('Data de publicacao')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.nome)
        return super().save(*args, **kwargs)

    def __str__(self):
        return f'{ESCOLHA_CATEGORIAS[self.categoria-1][1]} {self.nome} '
    
    
    
class Pedido(models.Model):
    status = models.IntegerField(choices=STATUS_PEDIDO, default = 1)
    usuario = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,)
    preco_total = models.FloatField(default=0)
    data_pub = models.DateTimeField('Data do pedido')


    def __str__(self):
        return f'Pedido id = {self.id}'
    
    def getStatus(self):
        return  self.status
    


class Venda(models.Model):
    quantidade = models.PositiveIntegerField()
    produto = models.ForeignKey(Produto, on_delete = models.PROTECT)
    pedido = models.ForeignKey(Pedido, on_delete = models.PROTECT)
    preco= models.FloatField(default=0)
    preco_total = models.FloatField(default=0)

    


    def __str__(self):
        return f'{self.produto} / Pedido id = {self.pedido.id}'
    
    class Meta:
        verbose_name = 'Venda'
        verbose_name_plural = 'Vendas'
    

lojaonline/main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class AtualizarCadastroForm(forms.Form):
    nome = forms.CharField(max_length=65)
    sobrenome = forms.CharField(max_length=65)
    email = forms.EmailField()

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(AtualizarCadastroForm, self).__init__(*args, **kwargs)


        self.fields['nome'].widget.attrs['value'] = self.user.first_name
        self.fields['nome'].widget.attrs['class'] = 'form-control'
        self.fields['sobrenome'].widget.attrs['value'] = self.user.last_name
        self.fields['sobrenome'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['value'] = self.user.email
        self.fields['email'].widget.attrs['class'] = 'form-control'



class LoginForm(forms.Form):
    username = forms.CharField(max_length=65)
    password = forms.CharField(max_length=65, widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password']:
            self.fields[fieldname].help_text = None
            self.fields[fieldname].widget.attrs['class'] = 'form-control'



class RegisterForm(UserCreationForm):
    class Meta:
        model=User
        fields = ['username','email','password1','password2']
   
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'email', 'password1', 'password2']:
            self.fields[fieldname].help_text = None
            self.fields[fieldname].widget.attrs['class'] = 'form-control'
        


class AdicionarCarrinhoForm(forms.Form):
    quantidade = forms.IntegerField(required=True)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

lojaonline/main/views.py
from datetime import datetime
from decimal import Decimal
from django.shortcuts import get_object_or_404, render, redirect
from django.template import loader
from django.contrib import messages
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseRedirect
from django.views import View
from django.views.decorators.http import require_http_methods
from django.contrib.auth import authenticate,  login

from .cart import Cart




from .models import Marca, Pedido, Venda, Produto

from .forms import AdicionarCarrinhoForm, AtualizarCadastroForm, LoginForm, RegisterForm




class BaseView(View):

    pedidos_pendentes = Pedido.objects.filter(status = 1).__len__()


    def get(self, request):



        cart = Cart(request)
        product_list = Produto.objects.order_by()
        template = loader.get_template("main/index.html")
        context = {"product_list": product_list,  'cart': cart, 'pedidos_pendentes': self.pedidos_pendentes}
        return HttpResponse(template.render(context, request))
    
class ProductTypeView(BaseView):
    product_type=''
    cat_number = 0

    def get(self, request):
        cart = Cart(request)
        product_list = Produto.objects.filter(categoria = self.cat_number).order_by()
        marca_list = Marca.objects.all()
        template = loader.get_template(f"main/{self.product_type}.html") 
        context = {"product_list": product_list, "marca_list": marca_list,  'cart': cart}
        return HttpResponse(template.render(context, request))
    
class MonitorView(ProductTypeView):
    product_type='monitor'
    cat_number=5

class FoneView(ProductTypeView):
    product_type='fone'
    cat_number=4

class MousepadView(ProductTypeView):
    product_type='mousepad'
    cat_number=3

class TecladoView(ProductTypeView):
    product_type='teclado'
    cat_number=2

class MouseView(ProductTypeView):
    product_type='mouse'
    cat_number=1

class BuscarView(BaseView):

    
    def get(self, request):
        cart = Cart(request)
        search_query = request.GET.get('search_query')
        product_list = Produto.objects.filter(nome__contains=search_query)
        template = loader.get_template("main/busca.html")
        context = {"product_list": product_list,  'cart': cart}
        return HttpResponse(template.render(context, request))
    

class LogarView(BaseView):

    def get(self, request):
        cart = Cart(request)
        form = LoginForm()

        if request.user.is_authenticated:
            return HttpResponse('Usuário já logado! Saia da conta para fazer novo login')
        else:
            return render(request, 'main/login.html', {'form': form, 'cart': cart})




    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],
                    password=cd['password'])
        if user is not None:
            if user.is_active:
                login(request, user)
                print('login sucesso')
                return HttpResponseRedirect('/')
        else:
            return HttpResponse('Usuário não existe ou senha incorreta!')


class CadastroView(BaseView):

    def get(self, request):
        cart = Cart(request)
        form = RegisterForm()
        return render(request, 'main/cadastro.html', {'form': form, 'cart': cart})
    def post(self, request):
        cart = Cart(request)
        form = RegisterForm(request.POST) 
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            messages.success(request, 'Cadastro realizado com sucesso!.')
            return redirect('/')
        else:
            return render(request, 'main/cadastro.html', {'form': form})

    
class CarrinhoView(BaseView):

    def get(self, request):
        cart = Cart(request)
        template = loader.get_template("main/carrinho.html")
        context = {'cart': cart}
        return HttpResponse(template.render(context, request))
    def post(self, request):
        cart = Cart(request)
        product = get_object_or_404(Produto, id = request.POST['id'])
        form = AdicionarCarrinhoForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            cart.add(product=product, quantity=cd['quantidade'],
            update_quantity=cd['update'])
        else:
            print('fail')
        return redirect("/carrinho")
    
class LimparCarrinhoView(BaseView):

    def post(self, request):
        cart = Cart(request)
        cart.clear()
        return redirect("/carrinho")


class ProcutoView(BaseView):

    def get(self, request, slug):
        cart = Cart(request)
        product= Produto.objects.get(slug=slug)
        template = loader.get_template("main/produto.html")
        context = {"product": product,  'cart': cart}
        return HttpResponse(template.render(context, request))
    
class RemoverProdutoView(BaseView):

    def post(self, request):
        cart = Cart(request)
        product = get_object_or_404(Produto, id = request.POST['id'])
        cart.remove(product)
        return redirect("/carrinho")

class FinalizarCompraView(BaseView):

    def post(self, request):
        if request.user.is_authenticated:
            cart = Cart(request)
            pedido = Pedido.objects.create(usuario = request.user, data_pub = datetime.now())
            pedido_preco_total = 0
            for item in cart:
                Venda.objects.create(quantidade = item['quantidade'], produto = item['product'], pedido = pedido,
                                     preco = item['preco'],
                                      preco_total = item['preco_total'] )
                pedido_preco_total += item['preco_total']
            pedido.preco_total = pedido_preco_total
            pedido.save()

            cart.clear()
            return redirect("/pedidos")
        else:
            return redirect("/logar")

class MinhaContaView(BaseView):

    def get(self, request):
        if request.user.is_authenticated:
            cart = Cart(request)
            form = AtualizarCadastroForm(user=request.user) 
            template = loader.get_template("main/minha-conta.html")
            context = {'cart': cart, 'form': form}
            return HttpResponse(template.render(context, request))
        else:
            return redirect("/logar")
    
    def post(self, request):
        return HttpResponse('post')

class PedidosView(BaseView):

    def get(self, request):
        if request.user.is_authenticated:
            cart = Cart(request)
            pedidos = reversed(Pedido.objects.filter(usuario = request.user).values())
            context = {'pedidos': pedidos, 'cart': cart}
            template = loader.get_template("main/pedidos.html")
            return HttpResponse(template.render(context, request))
        return redirect("/logar")

class PedidoView(BaseView):

    def get(self, request, pedido_id):

        pedido = Pedido.objects.filter(id = pedido_id).values()
        user_id = pedido[0]['usuario_id']
        if request.user.id == user_id:
            cart = Cart(request)
            template = loader.get_template("main/pedido.html")
            vendas = Venda.objects.filter(pedido=pedido_id)
            context = {'pedido': pedido[0], 'vendas': vendas, 'cart': cart}
            return HttpResponse(template.render(context, request))
        else:
            return HttpResponseForbidden()

lojaonline/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <link href="{% static 'main/style.css' %}" rel="stylesheet">


</head>

<body>





    <div class="container-fluid main">



        <div class="row topo">

            <div class="col-12 topo-coluna text-end">
                

                {% if request.user.is_anonymous == True %}
                <a href="/logar">login </a>|
                {% else %}
                Bem vindo(a) {{request.user}}! |
                <a href="{% url 'main:logout' %}">logout</a> |

                {% endif %}


                <a href="/cadastro">cadastro </a>|


                {% if request.user.username == 'admin' %}

                <h4><a href="/admin">{{pedidos_pendentes}} pedidos aguardando envio...</a></h4>


                {% endif %}



            </div>

        </div>




        <div class="row menu-navbar">

            <nav class="navbar navbar-expand-lg">
                <div class="container-fluid">
                    <a class="navbar-brand" href="/"><img class="logo" src="{% static 'main/logo-topo.png' %}"
                            alt="Brand image"></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <form class="d-flex" role="search" method="GET" action="{% url 'main:buscar' %}">
                            <input class="form-control me-2" type="search" placeholder="O que você procura?" name="search_query"
                                required aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Buscar</button>
                        </form>

                        <div>

                            <a href="/carrinho/">

                                <img class="carrinho-logo" src="{% static 'main/shopping-cart-64.png' %}">
        
            
        
                                </a>
        

                        </div>


                        <div class="block">

                            <div class="circle">
                                <p>
                                    {{cart | length}}
                                </p>
                            </div>
                        </div>

                        <div>
                            <a href="/minha-conta">Minha conta</a>


                        </div>





                    </div>

                </div>


            </nav>

        </div>

        <div class="row menu-escolhas">
            <div class="col-3">

            </div>
            <div class="col-6">

                <div class="row menu-escolhas-texto">

                    <div class="col-1"></div>
                    <div class="col-2 "><a href="/categoria/mouse" class="text-decoration-none text-reset">MOUSE</a>
                    </div>
                    <div class="col-2"><a href="/categoria/teclado" class="text-decoration-none text-reset">TECLADO</a>
                    </div>
                    <div class="col-2"><a href="/categoria/mousepad"
                            class="text-decoration-none text-reset">MOUSEPAD</a></div>
                    <div class="col-2"><a href="/categoria/fone" class="text-decoration-none text-reset">FONE</a></div>
                    <div class="col-2"><a href="/categoria/monitor" class="text-decoration-none text-reset">MONITOR</a>
                    </div>

                    <div class="col-1"></div>

                </div>


            </div>
            <div class="col-3">

                <div class="row menu-escolhas-texto">
                    <div class="col-8"></div>
                    <div class="col-2"><i class="bi bi-search"></i></div>
                    <div class="col-2"><i class="bi bi-bag"></i> </i></div>


                </div>

            </div>

        </div>

        <div class="row">
            {% load static %}
            <div class="col-4"><img src="{% static 'main/final-mouse.jpg' %} " alt="final-mouse"></div>
            <div class="col-4"><img src="{% static 'main/logo01.png' %}" alt="logo01.jpg"></div>
            <div class="col-4"><img src="{% static 'main/mouse-pad.jpg' %}" alt="mouse-pad.jpg"></div>


        </div>



        <div class="row site p-5">

            {% block content %}
            {% endblock content %}

        </div>

        <div class="row">



            <footer class="text-center text-white" style="background-color:#00050b">


                <!-- Copyright -->
                <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0);">
                    © 2023 Copyright:
                    <a class="text-white" href="#">finalstoreimports.com</a>

                </div>
                <!-- Copyright -->
            </footer>

        </div>

    </div>



</body>

</html>

lojaonline/main/templates/main/busca.html
{% extends "main/categoria.html" %}

{% block name %}
Resultado de busca
{% endblock name %}

lojaonline/main/templates/main/cadastro.html
{% extends "main/base.html" %}


{% block content %}
<hr>

<div class="d-flex justify-content-center ">
  <form class="w-50 border p-3" method="POST">

    <h2>Cadastro</h2>
    {% csrf_token %}

    <div class="row mb-3">
      <label for="inputEmail3" class="col-sm-2 col-form-label-lg ">Usuário</label>
      <div class="col-sm-10">
        {{form.username}}
      </div>
    </div>
    <div class="row mb-3">
      <label for="inputEmail3" class="col-sm-2 col-form-label-lg ">E-mail</label>
      <div class="col-sm-10">
        {{form.email}}
      </div>
    </div>
    <div class="row mb-3">
      <label for="inputPassword3" class="col-sm-2 col-form-label-lg">Senha</label>
      <div class="col-sm-10">
        {{form.password1}}
      </div>
    </div>
    <div class="row mb-3">
      <label for="inputPassword3" class="col-sm-2 col-form-label-lg">Confirmar</label>
      <div class="col-sm-10">
        {{form.password2}}
      </div>
    </div>

    <input class="btn-primary btn-lg" type="submit"  value="Cadastrar"/>
  </form>


</div>








{% endblock content %}

lojaonline/main/templates/main/carrinho.html
{% extends "main/base.html" %}


{% block content %}
<hr>


<div class="row">

    {% load static %}


    <div class="col-8">

        {% if cart|length == 0 %}

        <h1 class="text-center">Carrinho vazio!</h1>

        {% endif %}

        {% for item in cart %}
        {% with product=item.product %}


        <div class="card-dark mb-3 bg-dark w-80">
            <div class="row">
                <div class="col-md-2">

                    <a href=" /produto/{{product.slug}} " class="text-decoration-none text-reset">
                        <img src="{{product.foto.url}}" class="rounded img-fluid " alt="...">
                    </a>
                </div>
                <div class="col-md-6 align-self-center">
                    <div class="card-body text-center">
                        <h3 class="card-title">{{product}} ({{product.marca}})</h3>
                        <h5 class="card-text align-middle">Quantidade: {{item.quantidade}} </h5>
                        <h6 class="card-text align-middle">- / +</h65>

                    </div>


                </div>
                <div class="col-md-4">
                    <div class="card-body">



                        <h5 class="card-text">Preço/unidade: R$ {{product.preco}} </h5>
                        <h5 class="card-text">Preço total: R$ {{item.preco_total}} </h5>
                        <form name="remover" method="post" action="{% url 'main:remover' %}">
                            {% csrf_token %}
                            <input type="hidden" name="id" value="{{ product.id }}">
                                <input class="btn btn-link btn-lg" type="submit" value="Remover Produto" />
                        </form>
                




                    </div>


                </div>

            </div>
        </div>


        {% endwith %}
        {% endfor %}

    </div>

    <div class="col-4">



        <h1 class="text-center">{{cart | length}} produtos no carrinho</h1>
        <h1 class="text-center">Preço total: {{cart.get_total_price}} R$</h1>

        <form name="finalizar-compra" method="post" action="{% url 'main:finalizar-compra' %}">
            {% csrf_token %}
            <div class="text-center">
                <input type="hidden" name="cart" value="{{ cart }}">
                <input class="btn btn-success btn-lg" type="submit" value="Finalizar compra" />
            </div>


        </form>

        <form name="limpar_carrinho" method="post" action="{% url 'main:limpar-carrinho' %}">
            {% csrf_token %}
            <div class="text-center">
                <input class="btn btn-link btn-lg" type="submit" value="Limpar carrinho" />
            </div>

        </form>



    </div>


</div>








</div>

{% endblock content %}

lojaonline/main/templates/main/categoria.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
<h4>Home > Categoria >
    {% block name %}
    {% endblock name %}</h4>

<hr>




<div class="col-3">

<h5 class="text-primary">Aplicar filtros</h5>

    <script src="{% static 'main/checkbox_selection.js' %}"></script>

    <div class="row">
        <h4>Marca</h4>





        <ul class="list-unstyled">
            {% for marca in marca_list %}
            <li  onclick="select(this)"> 
                <input  class="form-check-input marca_checkbox" type="checkbox" id="input_marca" checked>
                <label class="form-check-label "  for="flexCheckChecked">
                   {{marca.nome}}
                </label>
            </li>
            {% endfor %}
        </ul>



    </div>

    <div class="row">
        <h4>Avaliação</h4>

        <ul class="list-inline">
            <li>5 estrelas</li>
            <li>4 estrelas</li>
            <li>3 estrelas</li>
            <li>2 estrelas</li>
            <li>1 estrelas</li>


        </ul>

    </div class="row">

    <div class="row">
        <h4>Preço</h4>

        <ul class="list-inline">
            <li>0-50R$</li>
            <li>50-150R$</li>
            <li>150-300R$</li>
            <li>>300R$</li>

        </ul>



    </div class="row">

    <div class="row"></div class="row">
    <div class="row"></div class="row">
    <div class="row"></div class="row">



</div>


<div class="col-9">


    <div class="product-list">

        <div class="row">
            {% if product_list %}
            <p>{{product_list|length}} produtos encontrados</p>
            {% else %}
            <p>Nenhum produto encontrado.</p>
            {% endif %}
        </div>

        <div class="row">


            {% if product_list %}
            {% for product in product_list %}
            <div class="col-4">

                <a href=" /produto/{{product.slug}} " class="text-decoration-none text-reset">

                    <div class="card-dark bg-dark mb-5" style="width: 18rem;">
                        <img src="{{product.foto.url}}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title ">{{ product }}  </h5>
                            <h6 class="card-title text-secondary">{{product.marca}} </h6>

                            <h4 class="card-text text-end ">
                                R$ {{ product.preco}} 

                            </h4>
                        </div>
                    </div>

                </a>

            </div>
            {% endfor %}
            {% endif %}


        </div>

    </div>
</div>




{% endblock content %}

lojaonline/main/templates/main/fone.html
{% extends "main/categoria.html" %}

{% block name %}
Fone
{% endblock name %}

lojaonline/main/templates/main/index.html
{% extends "main/base.html" %}


{% block content %}
<hr>
<h1 class="text-center">Promoções</h1>

{% endblock content %}

lojaonline/main/templates/main/login.html
{% extends "main/base.html" %}


{% block content %}
<hr>

<div class="d-flex justify-content-center ">
  <form class="w-50 border p-3" method="POST">

    <h2>Login</h2>
    {% csrf_token %}

    <div class="row mb-3">
      <label for="inputEmail3" class="col-sm-2 col-form-label-lg ">Usuário</label>
      <div class="col-sm-10">
        {{form.username}}
      </div>
    </div>
    <div class="row mb-3">
      <label for="inputPassword3" class="col-sm-2 col-form-label-lg">Senha</label>
      <div class="col-sm-10">
        {{form.password}}
      </div>
    </div>

    <input class="btn-primary btn-lg" type="submit" value="Login" />
  </form>


</div>





{% endblock content %}

lojaonline/main/templates/main/monitor.html
{% extends "main/categoria.html" %}

{% block name %}
Monitor
{% endblock name %}

lojaonline/main/templates/main/mouse.html
{% extends "main/categoria.html" %}

{% block name %}
Mouse
{% endblock name %}

lojaonline/main/templates/main/mousepad.html
{% extends "main/categoria.html" %}

{% block name %}
Mousepad
{% endblock name %}

lojaonline/main/templates/main/pedido.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
<h4>Home > Meus pedidos > Pedido número {{pedido.id}}</h4>



<hr>

<div class="row">

    <div class="col-8">


        <table class="table table-dark table-striped">
            <thead>
                <tr>
                    <th scope="col">Produto: </th>
                    <th scope="col">Preço </th>
                    <th scope="col">Quantidade </th>

                    <th scope="col">Preço total</th>
                </tr>
            </thead>
            <tbody>
                {% for venda in vendas %}


                <tr>


                    <th scope="row">
                        <a href=" /produto/{{venda.produto.slug}} ">

                            {{venda.produto}}</a>
                    </th>

                    <td>{{venda.preco}} R$</td>
                    <td>{{venda.quantidade}}</td>

                    <td>{{venda.preco_total}} R$</td>


                </tr>




                {% endfor %}


                <tr>


                    <th scope="row"></th>
                    <td></td>
                    <td></td>

                    <td class="fw-bold fs-3">{{pedido.preco_total}} R$</td>


                </tr>

            </tbody>
        </table>



    </div>


    <div class="col-4">

        <h4> {% if pedido.status == 1 %}
            Aguardando envio
            {% elif pedido.status == 2 %}
            Enviado
            {% elif pedido.status == 3 %}
            Entregue
            {% endif %}</h4>
        <h4></h4>

    </div>


</div>







{% endblock content %}

lojaonline/main/templates/main/pedidos.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
<h4>Home > Minha conta > Meus pedidos</h4>

<hr>




<table class="table table-dark table-striped">
    <thead>
        <tr>
            <th scope="col">ID do pedido</th>
            <th scope="col">Data do pedido</th>
            <th scope="col">Preço total</th>
            <th scope="col">Status</th>
        </tr>
    </thead>
    <tbody>
        {% for pedido in pedidos %}


        <tr>


            <th scope="row"><a href="/pedidos/{{pedido.id}}">{{pedido.id}}</a></th>
            <td>{{pedido.data_pub}}</td>
            <td>{{pedido.preco_total}} R$</td>
            <td>

                {% if pedido.status == 1 %}
                <div>Aguardando envio</div>
                {% elif pedido.status == 2 %}
                <div class="text-success">Enviado</div>
                {% elif pedido.status == 3 %}
                <div class="text-success">Entregue</div>
                {% endif %}
            </td>


        </tr>




        {% endfor %}
    </tbody>
</table>


{% endblock content %}

lojaonline/main/templates/main/teclado.html
{% extends "main/categoria.html" %}

{% block name %}
Teclado
{% endblock name %}